WebMvcTest/Models/MyDbContext.cs
namespace WebMvcTest.Models
{
    using System;
    using System.Data.Entity;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Linq;

    public partial class MyDbContext : DbContext
    {
        public MyDbContext()
            : base("name=MyDbContext")
        {
        }

        public virtual DbSet<m_persons> m_persons { get; set; }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
        }
    }
}

WebMvcTest/Models/m_persons.cs
namespace WebMvcTest.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class m_persons
    {
        public int Id { get; set; }

        [Required]
        [StringLength(100)]
        public string personId { get; set; }

        [Required]
        [StringLength(100)]
        public string personName { get; set; }

        public string mailAddress { get; set; }

        [StringLength(20)]
        [DisplayFormat(DataFormatString ="TEL.{0}")]
        public string phoneNumber { get; set; }

        [StringLength(200)]
        public string detail { get; set; }

        public DateTime createdDatetime { get; set; }

        public DateTime updatedDatetime { get; set; }
    }
}

WebMvcTest/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebMvcTest.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebMvcTest/Controllers/m_personsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebMvcTest.Models;

namespace WebMvcTest.Controllers
{
    public class m_personsController : Controller
    {
        private MyDbContext db = new MyDbContext();

        // GET: m_persons
        public ActionResult Index()
        {
            return View(db.m_persons.ToList());
        }

        // GET: m_persons/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            m_persons m_persons = db.m_persons.Find(id);
            if (m_persons == null)
            {
                return HttpNotFound();
            }
            return View(m_persons);
        }

        // GET: m_persons/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: m_persons/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,personId,personName,mailAddress,phoneNumber,detail,createdDatetime,updatedDatetime")] m_persons m_persons)
        {
            if (ModelState.IsValid)
            {
                db.m_persons.Add(m_persons);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(m_persons);
        }

        // GET: m_persons/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            m_persons m_persons = db.m_persons.Find(id);
            if (m_persons == null)
            {
                return HttpNotFound();
            }
            return View(m_persons);
        }

        // POST: m_persons/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,personId,personName,mailAddress,phoneNumber,detail,createdDatetime,updatedDatetime")] m_persons m_persons)
        {
            if (ModelState.IsValid)
            {
                db.Entry(m_persons).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(m_persons);
        }

        // GET: m_persons/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            m_persons m_persons = db.m_persons.Find(id);
            if (m_persons == null)
            {
                return HttpNotFound();
            }
            return View(m_persons);
        }

        // POST: m_persons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            m_persons m_persons = db.m_persons.Find(id);
            db.m_persons.Remove(m_persons);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public ActionResult DetailIndexParts(int id)
        {
            m_persons query = new m_persons();
            using (var db = new MyDbContext())
            {
                try
                {
                    query = db.m_persons.FirstOrDefault(a => a.Id == id);
                }
                catch (DbEntityValidationException ex)
                {
                    var errorMessage = "";
                    ex.EntityValidationErrors.SelectMany(error => error.ValidationErrors).ToList()
                        .ForEach(model => errorMessage = errorMessage + model.PropertyName + " - " + model.ErrorMessage);
                }
            }

            return PartialView("_DetailIndexParts", query);
        }

        public ActionResult DetailIndex()
        {
            List<m_persons> query = new List<m_persons>();
            using (var db = new MyDbContext())
            {
                try
                {
                    query = db.m_persons.Take(10).ToList();
                }
                catch (DbEntityValidationException ex)
                {
                    var errorMessage = "";
                    ex.EntityValidationErrors.SelectMany(error => error.ValidationErrors).ToList()
                        .ForEach(model => errorMessage = errorMessage + model.PropertyName + " - " + model.ErrorMessage);
                }
            }

            ViewData["names"] = query;

            return View();
        }

    }
}

WebMvcTest/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebMvcTest/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebMvcTest/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        @Html.ActionLink("Personマスタ", "index", "m_persons")
    </div>
    <div class="col-md-4">
        @Html.ActionLink("AJAXのドロップダウンメニュー", "DetailIndex", "m_persons")
    </div>
</div>

WebMvcTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - マイ ASP.NET アプリケーション</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("Header", required: false)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("アプリケーション名", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("ホーム", "Index", "Home")</li>
                    <li>@Html.ActionLink("詳細", "About", "Home")</li>
                    <li>@Html.ActionLink("問い合わせ", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - マイ ASP.NET アプリケーション</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @*@RenderSection(セクション名, required: 必須かどうか)*@
    @RenderSection("scripts", required: false)
</body>
</html>

WebMvcTest/Views/m_persons/Create.cshtml
@model WebMvcTest.Models.m_persons

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>m_persons</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.personId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.personId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.personId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.personName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.personName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.personName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.detail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.detail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.detail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.createdDatetime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdDatetime, new { htmlAttributes = new { @class = "caldate form-control" } })
                @Html.ValidationMessageFor(model => model.createdDatetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.updatedDatetime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.updatedDatetime, new { htmlAttributes = new { @class = "caldate form-control" } })
                @Html.ValidationMessageFor(model => model.updatedDatetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryui")

    <script type="text/javascript">
        $(function() {
            // テキストボックスへ Datepicker を仕掛ける
            $(".caldate").datepicker({
            buttonImageOnly: false,           // 画像として表示
            showOn: "focus"                   // カレンダー呼び出し元の定義
            });
 
            // 日本語化
            $.datepicker.regional['ja'] = {
            closeText: '閉じる',
            prevText: '<前',
            nextText: '次>',
            currentText: '今日',
            monthNames: ['1月','2月','3月','4月','5月','6月',
            '7月','8月','9月','10月','11月','12月'],
            monthNamesShort: ['1月','2月','3月','4月','5月','6月',
            '7月','8月','9月','10月','11月','12月'],
            dayNames: ['日曜日','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日'],
            dayNamesShort: ['日','月','火','水','木','金','土'],
            dayNamesMin: ['日','月','火','水','木','金','土'],
            weekHeader: '週',
            dateFormat: 'yy/mm/dd',
            firstDay: 0,
            isRTL: false,
            showMonthAfterYear: true,
            yearSuffix: '年'};
            $.datepicker.setDefaults($.datepicker.regional['ja']);
        });
    </script>
}

@section Header {
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet" />
}

WebMvcTest/Views/m_persons/Delete.cshtml
@model WebMvcTest.Models.m_persons


@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>m_persons</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.personId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.personId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.personName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.personName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdDatetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdDatetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updatedDatetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updatedDatetime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

WebMvcTest/Views/m_persons/DetailIndex.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>詳細</h2>

@using (Ajax.BeginForm(
    "DetailIndexParts",
    new AjaxOptions
    {
        UpdateTargetId = "result"
    }))
{
    @Html.DropDownList(
    "id",
        new SelectList(
            (System.Collections.IEnumerable)ViewData["names"],
            "id",
            "personName",
            "1"
            )
    )
    <input type="submit" value="詳細表示" />
}

<div id="result">
</div>

@section scripts {
    @Scripts.Render("~/bundles/ajax")
}

WebMvcTest/Views/m_persons/Details.cshtml
@model WebMvcTest.Models.m_persons

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>m_persons</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.personId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.personId)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.personName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.personName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mailAddress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.detail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.detail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdDatetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdDatetime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.updatedDatetime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.updatedDatetime)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

WebMvcTest/Views/m_persons/Edit.cshtml
@model WebMvcTest.Models.m_persons

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>m_persons</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.personId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.personId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.personId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.personName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.personName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.personName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.mailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.mailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.detail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.detail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.detail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.createdDatetime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdDatetime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createdDatetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.updatedDatetime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.updatedDatetime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.updatedDatetime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebMvcTest/Views/m_persons/Index.cshtml
@model IEnumerable<WebMvcTest.Models.m_persons>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <
<h2>Index</h2>
<p>
    @Html.ActionLink("Create New", "Create")
</p>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.personId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.personName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.mailAddress)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.detail)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.createdDatetime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.updatedDatetime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.personId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.personName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.mailAddress)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.phoneNumber)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.detail)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.createdDatetime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.updatedDatetime)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

WebMvcTest/Views/m_persons/_DetailIndexParts.cshtml
@model WebMvcTest.Models.m_persons

<div>
    <dl>
        <dt>
            @Html.DisplayNameFor(model => model.personId)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.personId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.personName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.personName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mailAddress)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.mailAddress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>
    </dl>
</div>